# Generated by Django 3.2.8 on 2021-11-01 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junkAPIs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorders',
            name='cart_items_details',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartorders',
            name='cart_items_keys',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartorders',
            name='cart_items_total_price',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
