# Generated by Django 3.2.8 on 2021-11-01 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junkAPIs', '0002_auto_20211101_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorders',
            name='cart_items_total_price',
            field=models.FloatField(default=0.0),
        ),
    ]
