# Generated by Django 3.2.8 on 2021-11-07 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junkAPIs', '0003_alter_cartorders_cart_items_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingorders',
            name='order_items',
            field=models.JSONField(),
        ),
    ]
