# Generated by Django 3.2.8 on 2021-11-07 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junkAPIs', '0004_alter_pendingorders_order_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvedorders',
            name='order_items',
            field=models.JSONField(),
        ),
    ]
