# Generated by Django 3.2.8 on 2021-11-10 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('junkAPIs', '0006_auto_20211107_2354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approvedorders',
            old_name='user',
            new_name='junkuser_customer',
        ),
        migrations.RenameField(
            model_name='pendingorders',
            old_name='user',
            new_name='junkuser_customer',
        ),
    ]
